### PR TITLE
looping retries

### PR DESCRIPTION
**Pull request by tobowers**
@brandonwestcott found an intermittent test failure, documented in #40. This adds a fix for that failure and another one I noticed while debugging. This just retries the commands until the notfound is gone.

This fixes the spec, one wonders if this should be in the SDK somewhere, but it's not immediately obvious how to do that generically.

### CODE REVIEW

**Comment by brandonwestcott** [comment]
@tobowers so to restate to make sure I'm understanding clearly:

The community CurrentState message is coming in over the pubsub, which is triggering the `nextUpdate`, but that may not yet contain the tip of the chaintree we are expecting?

If thats the case, maybe a new method (ex `nextUpdateFor(did)`) that would get current tip, poll `nextUpdate`, and return promise once it sees a new tip for that did?

**Comment by tobowers** [comment]
nextUpdate is fired the next time a community tip gets published, regardless of any content of the tip... it's not really designed for waiting for things.

**Comment by tobowers** [comment]
oh I see your suggestion now... just whenever there is a new tip, check it for the DID... but then we'd have to pass in the original tip I guess to see if it's diverged.

**Comment by brandonwestcott** [comment]
@tobowers yeah passing the original tip is probably better than fetching the current tip function init, could get some odd race conditions in there. But probably don't need to rush to fix, i'm good with getting a bit more usage before we rush a fix.

**Pull request merged**
