### PR TITLE
export tupelo waitForRound function

### PR DESCRIPTION
**Pull request by zonotope**

### CODE REVIEW

**Comment by tobowers** [comment]
this is missing the go-sdk part, right?

**Comment by zonotope** [comment]
@tobowers you mean [this](https://github.com/quorumcontrol/tupelo-go-sdk/blob/master/wasm/jsclient/jsclient.go#L186-L199) and [this](https://github.com/quorumcontrol/tupelo-go-sdk/blob/master/wasm/main.go#L141-L143)?

**Comment by tobowers** [comment]
re-running tests

**Comment by tobowers** [comment]
@zonotope the diff here is only showing a go-sdk change now.

**Pull request merged**
