### PR TITLE
Update examples for gossip4

### PR DESCRIPTION
**Pull request by cap10morgan**
I'm pointing them at the local tupelo-wasm-sdk for this, which may or may not be what we want. Building the SDK itself before running the examples doesn't seem _too_ bad now that the go-sdk is open source. But I'm open to other suggestions. I like that this is more hermetic, but I'm not committed to it.

I didn't actually have to change the examples, but I fixed a couple of deprecation warnings in `resolve`.

[Trello card](https://trello.com/c/SYPyJrGY)

### CODE REVIEW

**Comment by cap10morgan** [comment]
Not quite ready yet. Need to rethink how the GH Actions work.

**Comment by cap10morgan** [comment]
OK this is ready for review now. CI test is still failing, but it's the same one that was failing before, so unrelated to this PR. I'll dig into that separately.

**Comment by cap10morgan** [comment]
Test failure should be fixed by #82.

**Comment by cap10morgan** [comment]
> I'm waffling a bit on the local path vs npm package for the examples. "checkout and run" is a nice value add for examples imho, but the tradeoff of divergent local code from example code isn't great.

I think we can get back to "checkout and run" with some added automation and tooling. Basically have it build the local WASM on demand when you run an example and it's missing or outdated.

> If we go with the local path, can we go ahead and update the `npm build` to not require any local go deps (now that all repos are public) so that the barrier to running is lower?

SGTM! What are the local go deps? AFAICT it was fetching remote deps w/ an SSH key when they were private, which I think I've switched to being all public HTTPS now. But if I've missed anything I'm happy to update it.

**Comment by cap10morgan** [comment]
Ugh. Test whack-a-mole. Now a _different_ test keeps failing after merging in the "wait on at least 2/3 signers" change was merged. 😖

**Comment by cap10morgan** [comment]
Waiting longer seems to have helped. May just be anemic GH action runtime environment.

**Comment by brandonwestcott** [comment]
> SGTM! What are the local go deps? AFAICT it was fetching remote deps w/ an SSH key when they were private, which I think I've switched to being all public HTTPS now. But if I've missed anything I'm happy to update it.

I _think_ just making https://github.com/quorumcontrol/tupelo-wasm-sdk/blob/master/scripts/build-wasm.sh full docker so `go` isn't required locally.

**Comment by cap10morgan** [comment]
@brandonwestcott Good call. Latest commit builds WASM even if I `brew unlink go` first.

**Pull request merged**
