### PR TITLE
cleanup tests

### PR DESCRIPTION
**Pull request by tobowers**
This is just #53 but against master.

### CODE REVIEW

**Comment by tobowers** [comment]
@brandonwestcott so this was failing because previously the `getFresh...` was returning a new community and all the tests were stopping them which means the next test would error. I removed the stop, but now all the tests are using a global which is also probably not ideal.

**Comment by brandonwestcott** [comment]
@tobowers ah I missed that, my fault - we could use `beforeEach` and `afterEach` to do a fresh community on each?

**Comment by brandonwestcott** [comment]
happy to make that change if its 👍

**Comment by tobowers** [comment]
tests pass here so let's merge we can revisit on fresh community.

**Pull request merged**
